name = "Digital Gardenscape"
license = "GNU Affero General Public License v3.0"
licenselink = "https://github.com/cutthroat78/hugo-digital-gardenscape-theme/blob/main/LICENSE"
description = "Another Hugo Theme for Digital Gardens"
homepage = "https://github.com/cutthroat78/hugo-digital-gardenscape-theme"
demopage = "_"
tags = []
features = []
min_version = "0.112.3"

[author]
  name = "Sionnach"
  homepage = "https://sionnach.xyz/"
